Repository openscilab/reserver, pull requests merged in 2024-04, with the labels that each got.

#20 Feature/batch operation
  CHANGELOG.md
  reserver/__init__.py
  reserver/reserver_obj.py
  tests/test_reserver.py
Labels: new feature

#22 Modern templates added
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  CHANGELOG.md
  otherfiles/RELEASE.md
  otherfiles/version_check.py
Labels: enhancement

#23 Minor edits applied
  AUTHORS.md
  README.md
  dev-requirements.txt
  requirements.txt
  reserver/reserver_obj.py
  tests/test_reserver.py
Labels: enhancement

#24 SECURITY.md
  .github/CODE_OF_CONDUCT.md
  .github/workflows/test.yml
  AUTHORS.md
  CHANGELOG.md
  README.md
  SECURITY.md
  otherfiles/RELEASE.md
  otherfiles/version_check.py
  setup.py
Labels: documentation, minor
